generator:
  - conv_encoder_decoder
  - idcgan
  - unet1
  - unet2
  - unet3
  - unet4
  - unet5
  - unet6
  - unet7
  - pix2pix
  - unet5_residual
  - unet5_contextdilated
  - unet5_scan
  - unet5_recursive
  - unet5_attention
  - unet5_dense
  - unet5_ddb15x1
  - unet5_scu
  - unet5_ddb15x1_scu
discriminator:
  - discriminator